services:
  postgres:
    image: postgres:17.5-bookworm
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: naku
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
